name: proxiMarkt

services:
  php:
    build: ./php
    user: 1000:1000
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
      MYSQL_DB: proxiMarkt
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
      MYSQL_DATABASE: proxiMarkt
    volumes:
      - proxiMarkt:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  proxiMarkt: